### ISSUE TITLE
With the latest version, context menu is not working

### ISSUE THREAD

**Issue by manikumarrepuri** [patorjk/d3-context-menu#36]
My application was installed with latest d3-context-menu which is 1.0.1. Unfortunately, context menu has stopped working and doesn't spit any errors.

Verified with previous versions, worked alright!

**Comment by patorjk** [comment]
Do you have an example? And what is happening, is the menu just not showing up? I installed from npm and tried out the example in /example and it seemed to work fine.

**Comment by manikumarrepuri** [comment]
I have not done any changes to my code in recent days.

Rebuilt my dev machine, it seemed to be installed the latest version of
context menu. It just doesn't show anything on right click.

I quickly did a test copying the d3-context-menu.js code from the Plunker
you have posed in Git. It's working.

But with the installed version, it's not.

Thanks,
Mani

**Comment by adrianbota** [comment]
Hi @manikumarrepuri,

Which version were you using before? Latest version may not be backwards compatible in certain situations. Try explicitly setting a version in your `package.json`, if you are not yet ready to upgrade your code to work with the latest version. You can find the available versions in the README page

**Comment by terocohu** [comment]
I started to see the same problem. It is because in d3-context-menu.js where it makes it visible:
	// display context menu
				d3.select('.d3-context-menu')
					.style('left', (d3.event.pageX - 2) + 'px')
					.style('top', (d3.event.pageY - 2) + 'px')
					.style('display', 'block');  <--- THIS LINE DOES NOT EXISTS IN THE LATEST VERSION, MENU WILL STAY HIDDEN

				d3.event.preventDefault();

@manikumarrepuri  @adrianbota

**Comment by patorjk** [comment]
@terocohu What browser are you using? And you can confirm that adding that line back causes the menu to work correctly again?

The menu seems to work fine for me with and without the line (both in Firefox and Chrome on Mac). I'm not sure why it was taken out, but if it fixes the problem you're encountering I can put it back in.

**Comment by terocohu** [comment]
Hi Patorjk,

Thanks for the quick response. 

I confirm that **adding that line fixes this issue** at least in Chrome, Safari and Firefox browser (running in Mac), where it **is broken without it**.

If you check the element in element inspector, it is missing the display: block, when this problem occurs. 

For a while I was wondering why I got inconsistent results on my and on our server machine. That turnout to be issue of caching the bower_components on my machine where server got always the latest. Could you be experiencing also that?

Please put that line back. 

I also experience the problem, that I cannot request a certain (0.1.2) version of the package (causes . Only the "latest" works). 

That shows error:
_$ node_modules/bower/bin/bower install --allow-root
bower not-cached    https://github.com/patorjk/d3-context-menu.git#0.1.2
bower resolve       https://github.com/patorjk/d3-context-menu.git#0.1.2
bower ENORESTARGET  No tag found that was able to satisfy 0.1.2

Additional error details:
No versions found in https://github.com/patorjk/d3-context-menu.git
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command._

I get the same result also if I fix to version 1.0.1 which is supposedly the latest.

**Comment by patorjk** [comment]
I'll update the package and repo tonight with that line added back in.

I've been looking into the bower issue, I'm not sure what's causing it (there's another issue open about it). Installing the latest version works, though trying to get a version by its version number leads to an error. However, you can still install by the commit number and it'll work that way (ex: "bower install d3-context-menu#9b9c146", from: https://github.com/patorjk/d3-context-menu/commits/master).

**Comment by manikumarrepuri** [comment]
Thank you so much.


-Mani

**Comment by patorjk** [comment]
Updated in version 1.0.2.

**Comment by adrianbota** [comment]
@terocohu are you sure your code/css doesn't hide the context menu? To me, that `.style('display', 'block')` doesn't make sense with the latest code, because the d3-context-menu is no longer hidden either from css or js, instead it's appended to the DOM when shown, and then removed from the DOM when hidden. We have version 1.0.1 working in a staging environment and it has been tested thoroughly. We haven't seen this issue.

Also I had not trouble installing v 0.1.2 via npm using `npm install d3-context-menu@0.1.2`. Bower installation should probably be deprecated, even their official websites suggests that there are better alternatives these days: https://bower.io/ see `...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!`

**Comment by adrianbota** [comment]
Also I suggest clearing the caches:
 - browser cache after upgrading and running the latest version
 - npm cache (delete `node_modules` and `npm install` again)
 - bower cache (`bower cache clean`)
 
Also make sure you don't need admin privileges to run the commands (you might need to run the install commands with `sudo`)

**Comment by terocohu** [comment]
Hi,

I do not have more time to investigate the root cause. What I experienced
on my Firefox, Chrome and Safari browsers, I have shared. Caching was not
an issue. I manually deleted the library and installed it. The only change
I made was the one I have described.

After your fix was deployed (adding the display: block) our server
environment version started to work again, so I can confirm that it does
make a change for what ever reason.

Perhaps would be enough to set display: block in the css.

Br,
Tero



www.spacenation.org

*Tero Viitala-Kiss*
CTO

+358 5 <+358%2040%205673344>0 486 9473
tero@spacenation.org

Skype: terinko


*Unearth your potential. Discover your Space. No Borders.*
