### ISSUE TITLE
Using Angular directives

### ISSUE THREAD

**Issue by Pyo25** [patorjk/d3-context-menu#4]
Hello Pat, 

According to you, what we would be the best way to use the context-menu into an Angular app ? 
For instance I'd like to use Angular directives as titles.

Regards

**Comment by patorjk** [comment]
Every time the context menu is shown, the HTML for its items is placed into the DOM. Since this action exists outside of the Angular digest cycle, you'd have to compile the HTML manually with Angular's $compile service. The way you'd do that is you'd inject the $compile service into the controller/service/directive the context menu exists in, and then execute the $compile call in the title function's return statement. Example:

app.directive(function($compile)) { 
...
var menu = [
    {
        title: function() {
                var yourHtml = '{{someVar}}';
                return $compile(yourHtml)($scope);
        },
        action: function(elm, d, i) {
            console.log('Item #1 clicked!');
        }
    }
]
...
} // end directive

I didn't test that, but it should work. Let me know if it doesn't.

**Comment by Pyo25** [comment]
Thank you for your answer.

Finally as I needed more customization and modularization, I created a new directive inspired from your context-menu. 

When a there is `contextmenu` event in D3, I `dispatch` an event that is caught by my directive which is then displayed with the given data.

**Comment by patorjk** [comment]
Sounds good, glad you were able to figure something out.
